name: Test Docker Build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test-build:
    name: Test Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t livecards-test .

      - name: Test image functionality
        run: |
          # Test that the image can start and show help
          docker run --rm livecards-test --help

          # Test server startup
          docker run -d --name test-server -p 8000:8000 livecards-test

          # Wait for server to start
          sleep 15

          # Test health endpoint
          curl -f http://localhost:8000/health || exit 1

          # Test main endpoint (should redirect)
          curl -f -I http://localhost:8000/ || exit 1

          # Clean up
          docker stop test-server
          docker rm test-server

      - name: Test image size
        run: |
          # Check that the image is reasonably sized
          IMAGE_SIZE=$(docker images livecards-test --format "{{.Size}}" | sed 's/[^0-9]//g')
          echo "Image size: ${IMAGE_SIZE}MB"

          # Fail if image is too large (>500MB)
          if [ "$IMAGE_SIZE" -gt 500 ]; then
            echo "Image is too large: ${IMAGE_SIZE}MB"
            exit 1
          fi
