name: Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: "1.86.0"

jobs:
  build:
    name: Build (${{ matrix.target.target }})
    runs-on: ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            test: true
            cross: false
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            test: false
            cross: true
          - os: macos-latest
            target: x86_64-apple-darwin
            test: true
            cross: false
          - os: macos-latest
            target: aarch64-apple-darwin
            test: true
            cross: false
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            test: true
            cross: false
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            test: false # cross-compilation is not required, but we can't test it natively
            cross: false
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.target.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cross
        if: matrix.target.cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build project (native)
        if: ${{ matrix.target.cross == false }}
        run: cargo build --release --target ${{ matrix.target.target }}

      - name: Build project (cross-compilation)
        if: ${{ matrix.target.cross == true }}
        run: cross build --release --target=${{ matrix.target.target }} --features vendored-openssl

      - name: Install nextest
        if: ${{ matrix.target.test == true && matrix.target.cross == false }}
        uses: taiki-e/install-action@nextest

      - name: Run tests (native)
        if: ${{ matrix.target.test == true && matrix.target.cross == false }}
        run: cargo nextest run --verbose --target ${{ matrix.target.target }} --profile ci

      - name: Run tests (cross-compiled)
        if: ${{ matrix.target.test == true && matrix.target.cross == true }}
        run: cross test --verbose --features vendored-openssl,no-threading-tests --target ${{ matrix.target.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: glim-${{ matrix.target.target }}
          path: |
            target/${{ matrix.target.target }}/release/glim
            target/${{ matrix.target.target }}/release/glim.exe
          if-no-files-found: error
