name: Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: "1.86.0"

jobs:
  test:
    name: Test (${{ matrix.feature }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        feature: [cli, server]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/install-action@nextest

      - name: Run tests
        run: cargo nextest run --verbose --features ${{ matrix.feature }}

  build:
    name: Build (${{ matrix.target.target }}, ${{ matrix.feature }})
    runs-on: ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc
        feature: [cli, server]
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.target.target }}

      - uses: Swatinem/rust-cache@v2

      - name: Install Linux dependencies
        if: matrix.target.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libssl-dev \
            gcc-aarch64-linux-gnu \
            libc6-dev-arm64-cross \
            crossbuild-essential-arm64

      - name: Setup cross-compilation environment
        if: matrix.target.os == 'ubuntu-latest' && matrix.target.target == 'aarch64-unknown-linux-gnu'
        run: |
          # Add ARM64 architecture and configure package sources properly
          sudo dpkg --add-architecture arm64

          # Create proper sources.list configuration for cross-compilation
          sudo tee /etc/apt/sources.list.d/cross-compile.sources > /dev/null << 'EOF'
          Types: deb
          URIs: http://archive.ubuntu.com/ubuntu/
          Suites: noble noble-updates noble-backports
          Components: main universe restricted multiverse
          Architectures: amd64 arm64
          Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

          Types: deb
          URIs: http://archive.ubuntu.com/ubuntu/
          Suites: noble-security
          Components: main universe restricted multiverse
          Architectures: amd64 arm64
          Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
          EOF

          # Update package lists
          sudo apt-get update

          # Install cross-compilation tools and ARM64 packages
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            libc6-dev-arm64-cross \
            libssl-dev:arm64 \
            gcc-13 gcc-13-aarch64-linux-gnu

          # Set up cross-compilation environment variables
          # echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          # echo "CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++" >> $GITHUB_ENV
          # echo "AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar" >> $GITHUB_ENV
          # echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

          # # Set up OpenSSL for cross-compilation using ARM64 libraries
          # echo "PKG_CONFIG_SYSROOT_DIR=/usr/lib/aarch64-linux-gnu" >> $GITHUB_ENV
          # echo "OPENSSL_DIR=/usr" >> $GITHUB_ENV
          # echo "OPENSSL_LIB_DIR=/usr/lib/aarch64-linux-gnu" >> $GITHUB_ENV
          # echo "OPENSSL_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV

      - name: Setup native Linux environment
        if: matrix.target.os == 'ubuntu-latest' && matrix.target.target == 'x86_64-unknown-linux-gnu'
        run: |
          # Ensure native build has proper OpenSSL setup
          # echo "OPENSSL_DIR=/usr" >> $GITHUB_ENV
          # echo "OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
          # echo "OPENSSL_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV

      - name: Install macOS dependencies
        if: matrix.target.os == 'macos-latest'
        run: |
          brew install pkg-config openssl@3
          # Set up OpenSSL environment variables for macOS
          # echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
          # echo "OPENSSL_LIB_DIR=$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV
          # echo "OPENSSL_INCLUDE_DIR=$(brew --prefix openssl@3)/include" >> $GITHUB_ENV
          # echo "PKG_CONFIG_PATH=$(brew --prefix openssl@3)/lib/pkgconfig" >> $GITHUB_ENV

      - name: Build project
        run: cargo build --target ${{ matrix.target.target }} --features ${{ matrix.feature }}
